from dataclasses import dataclass, field, asdict
import json
from typing import Any, Dict, List, Optional

import panel as pn
import panel_material_ui as pmui
import param
import pandas as pd

from panel.widgets.base import WidgetBase
from panel.custom import PyComponent

import brimfile as bls
from brimfile.validation.json_descriptor import generate_json_descriptor
from brimfile.file_abstraction import sync

import zarr


from .utils import catch_and_notify
from .logging import logger




class BlsZarrInfo(WidgetBase, PyComponent):
    """
    A widget to display the general file information

    For Pyodide (ie `panel convert`) reasons, we use a side-effect way to
    update the tabulator's data.
    """

    value = param.ClassSelector(
        class_=bls.Data,
        default=None,
        allow_refs=True,
        doc="The names of the features selected and their set values",
    )

    def __init__(self, **params):
        self.title = pn.pane.Markdown("## Zarr file information")
        super().__init__(**params)

        self.info_tabulator = pn.widgets.Tabulator(
            show_index=False,
            disabled=True,
            visible=True,
            hidden_columns=["Group"],
        )

        # Dialog window
        self.dialog_text = pn.pane.Markdown("")
        self.dialog_tabulator = pn.widgets.Tabulator(
            show_index=False,
            disabled=True,
            visible=True,
            groupby=["Group"],
            hidden_columns=["Group"],
        )
        self.dialog = pmui.Dialog(
            self.dialog_text,
            pn.Row(
                pn.pane.Markdown("### Attributes"),
                pn.widgets.TooltipIcon(value="This table shows the attributes of the selected Zarr node. If it's empty, try clicking on another node and then back on the original."),
            ),            
            self.dialog_tabulator,
            open=False,
            close_on_click=True,
            title="Zarr node details",
            show_close_button=True,
        )

        # Explicit annotation, because param and type hinting is not working properly
        self.value: bls.Data
        logger.info("BlsZarrInfo initialized")

    @param.depends("value")
    @catch_and_notify(prefix="<b>Zarr file size: </b>")
    def _size_widget(self):
        if self.value is None:
            return pn.pane.Markdown("")

        store = self.value._file._store
        size = sync(store.getsize_prefix("/"))
        readable_size = bytes_human_string(size)
        return pn.pane.Markdown(f"Reported file size: **{readable_size}** (= {size} bytes)")

    @param.depends("value", watch=True)
    @catch_and_notify(prefix="<b>Zarr file info: </b>")
    def _info_widget(self):
        if self.value is None:
            self.info_tabulator.value = None
            return 
        root: zarr.Group = self.value._file._root
        group_info = sync(root.info_complete())
        # gropu info is a dataclass
        self.info_tabulator.value = dict_to_tabulator_df(asdict(group_info))

    @param.depends("value")
    @catch_and_notify(prefix="<b>Update Zarr tree: </b>")
    def _tree_widget(self):
        if self.value is None:
            return None

        root = self.value._file._root

        def brimfilejson_to_paneltree(brimfile_descriptor):
            """
            Convert the json_descriptor generated by brimfile into a list of TreeNode,
            that can be processed by pmui.Tree
            """

            def convert_node(node: dict, node_name):
                attributes: dict = node["attributes"]
                node_type: str = node["node_type"]
                if node_type == "group":
                    children = node.keys() - {"attributes", "node_type"}
                    return TreeNode(
                        label=node_name,
                        items=[convert_node(node[child], child) for child in children],
                        attributes=attributes,
                        node_type=node_type,
                    )
                elif node_type == "array":
                    attributes.update({"shape": node["shape"], "dtype": node["dtype"]})
                    return TreeNode(
                        label=node_name,
                        secondary=f"shape: {node['shape']} ; dtype: {node['dtype']}",
                        attributes=attributes,
                        node_type=node_type,
                    )
                else:
                    return None

            children = brimfile_descriptor.keys() - {"attributes", "node_type"}
            return [convert_node(brimfile_descriptor[key], key) for key in children]

        logger.info("Converting json_descriptor to pmui.Tree format")
        json_tree = generate_json_descriptor(root)
        tree = json.loads(json_tree)
        typed_tree = brimfilejson_to_paneltree(tree)
        dict_tree = [asdict(node) for node in typed_tree]
        tree = pmui.Tree(
            items=dict_tree,
            expanded=[(0,), (0,0,), (0,0,0,)],
            #sizing_mode="stretch_width",
            width_policy="fit",
        )

        tree.on_action("Details", self._tree_details_callback)
        return tree

    def _tree_details_callback(self, item):
        logger.info(f"Clicked on item: {item['label']}")
        dataframe = dict_to_tabulator_df(item["attributes"])
        self.dialog_tabulator.value = dataframe
        self.dialog_text.object = (
            f"Clicked on node: _{item['label']}_."  # TODO: Display the absolute path
        )
        self.dialog.open = True

    def __panel__(self):
        return pn.Column(
            self.title,
            self._size_widget,
            pn.layout.Divider(height=10, margin=10),
            pn.FlexBox(
                pn.Column(
                    pn.pane.Markdown("### Zarr file structure"),
                    self._tree_widget,                    
                ),
                pn.Column(
                    pn.pane.Markdown(f"### Zarr file info"),
                    self.info_tabulator,
                ),
                sizing_mode="stretch_width",
            ),
            self.dialog,
            sizing_mode="stretch_width",
        )


@dataclass
class TreeNode:
    """
    A class representing a node in the tree structure.
    Expected to be consumed by the pmui.Tree component: you first need to convert
    it into a dictonary with `asdict()` before passing to the Tree widget.

    Contains some shared code between different node type.
    """

    label: str
    icon: Optional[str] = None
    secondary: Optional[str] = None
    buttons: List[Dict[str, str]] = field(
        default_factory=lambda: [{"label": "Details", "icon": "info"}]
    )
    attributes: Dict[str, Any] = field(default_factory=dict)
    node_type: str = "group"  # or "array"
    items: List["TreeNode"] = field(default_factory=list)

    def __post_init__(self):
        icon_by_node_type = {
            "group": "folder",
            "array": "dataset",
        }
        if self.icon is None:
            self.icon = icon_by_node_type.get(self.node_type, "folder")


def dict_to_tabulator_df(data: dict) -> pd.DataFrame:
    rows = []

    def walk(d, path=None):
        path = path or []

        for key, value in d.items():
            if isinstance(value, dict):
                walk(value, path + [key])
            else:
                rows.append(
                    {
                        "Group": "/".join(path) if path else None,
                        "Name": key,
                        "Value": value,
                    }
                )

    walk(data)

    return pd.DataFrame(rows)

def bytes_human_string(num_bytes):
    for unit in ['B', 'KB', 'MB', 'GB', 'TB']:
        if num_bytes < 1024.0:
            return f"{num_bytes:.2f} {unit}"
        num_bytes /= 1024.0
    return f"{num_bytes:.2f} PB"