name: Build and Push Docker Image to GHCR

on:
  push:
    tags:
      - '*'   # runs on any tag push
  workflow_dispatch:  # Allows you to trigger the workflow manually

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository_owner }}/brimview:latest

jobs:
  docker:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write    # Needed to push to GHCR

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          IMAGE_NAME=${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}
          docker build --secret id=ADMIN_ENDPOINT,env=${{ secrets.ADMIN_PANEL_ENTRYPOINT}} --pull -t $IMAGE_NAME .
      
      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ${{ env.REGISTRY }} -u ${{ github.actor }} --password-stdin

      - name: Push Docker image to GHCR
        run: |
          IMAGE_NAME=${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}
          docker image push $IMAGE_NAME